### ISSUE TITLE
Possible to use on accounts with two-factor auth enabled?

### ISSUE THREAD

**Issue by frozenpandaman** [ioantsaf/hacked_insta_unliker#4]
Thank you so much for this script. Is there any way around the `two_factor_required` error thrown when your account has 2FA turned on, or should I just remove it & re-enable it on my account after I'm done running the script?

My account has liked so many posts that I'll likely have to run this script across multiple times/days and I ideally wouldn't want to leave 2FA turned off (or to go back and forth with enabling it) that whole time. Thanks!

**Comment by ioantsaf** [comment]
Currently there is no way to use the script with 2FA.
You will have to turn off 2FA, use the script then turn it on again. I also don’t plan on developing new features, but if someone wants to develop a 2FA method, feel free to submit a pull request.

**Comment by frozenpandaman** [comment]
Thanks for the answer! No worries. Apparently someone's made a fork of another JS-backed Instagam private API repo at https://github.com/ini0n/instagram-private-api-auth, which includes support for 2FA, so this should be possible in theory if anyone wants to tackle it in the future.
